In [2]:

library(readxl)
library(haven)
library(tidyverse)


my_data <- read.csv("/content/Sample_Dataset_2019.csv")

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [5]:

## Part 2: Data Management ###################################################

##### Step 1: Look at the data we imported into R ############################

#' View the data as a table in a pop-up window using View()

View(my_data)


#' Look at first and last 5 rows of the dataframe using head() and tail()

head(my_data)

tail(my_data)

#' Print the names of the variables in the dataframe using colnames()

colnames(my_data)


#' Print the types of all variables in the dataframe str()

str(my_data)

#' Print min/max/median for all variables in the dataframe using summary()

summary(my_data)

    ids   bday       Gender Age Athlete Smoking Height Weight Mile MileMinDur ⋯
1   20055 1995-08-06  0     24  1        1      64.5   127.5  494  0:08:14    ⋯
2   20075             0     NA  0        1      74.0   195.5  441  0:07:21    ⋯
3   20087             0     NA  0        1      68.5   153.0   NA             ⋯
4   20088 2001-01-08  1     18  0       NA      67.5   158.5  514  0:08:34    ⋯
5   20135 1998-12-26  0     20  0        1      75.0   152.0  450  0:07:30    ⋯
6   20161 2000-12-02  1     18  1        1      73.5   177.5  403  0:06:43    ⋯
7   20188 2001-08-06  0     18  0        1      76.0   181.0   NA             ⋯
8   20215 1997-08-05  0     22  0        2      76.0   155.5  563  0:09:23    ⋯
9   20250 1994-12-14 NA     24  0        1      66.5   119.0  653  0:10:53    ⋯
10  20354 1999-08-05  1     20  0        1      62.5   147.5  684  0:11:24    ⋯
11  20640 2000-05-31  1     19  0        1      63.0   161.0  798  0:13:18    ⋯
12  20739 1999-06-23  1     20  0        1      72.0   190.5  612  0:10:12    ⋯
13  20990 1998-06-08  1     21  1        1      64.0   118.0  423  0:07:03    ⋯
14  21077 1998-01-10  1     21  0        1      66.5   190.0  609  0:10:09    ⋯
15  21096             0     NA  1        1      74.0      NA  381  0:06:21    ⋯
16  21238 1998-12-22  0     20  1        1      68.0   132.5  426  0:07:06    ⋯
17  21383 1998-10-04  0     20  1        1      72.0      NA  377  0:06:17    ⋯
18  21472 1999-04-26  0     20  0        1      65.5      NA  507  0:08:27    ⋯
19  21488 1998-09-28  1     20  0       NA      65.0   131.0  386  0:06:26    ⋯
20  21498             1     NA  1        1      62.5   148.5  430  0:07:10    ⋯
21  21505 1999-11-06  0     19  0        1      63.5   116.5  337  0:05:37    ⋯
22  21615 1998-11-07  0     20  0        1      73.5   201.0  537  0:08:57    ⋯
23  21676 1999-09-26  1     19  0        1      72.0   214.0  616  0:10:16    ⋯
24  21861 1999-05-23  0     20  1        3      75.5   186.0  393  0:06:33    ⋯
25  21941 1999-03-23  1     20  0        1      59.0   128.5  558  0:09:18    ⋯
26  21993 1999-05-20  1     20  0        1        NA      NA  666  0:11:06    ⋯
27  22054 2000-07-29  1     19  1        1      66.0   146.5  473  0:07:53    ⋯
28  22088 1996-02-03  1     23  1        1      65.0   147.5  347  0:05:47    ⋯
29  22210 1998-12-25  1     20  1        1      67.0   170.0  427  0:07:07    ⋯
30  22224             0     NA  0        1        NA   187.0  355  0:05:55    ⋯
⋮   ⋮     ⋮          ⋮      ⋮   ⋮       ⋮       ⋮      ⋮      ⋮    ⋮          ⋱
406 48111 1998-03-29 NA     21  0       1       63.0   144.0  769  0:12:49    ⋯
407 48120 2000-08-26  0     19  1       3         NA   167.0  329  0:05:29    ⋯
408 48175 1998-08-08  1     21  0       1       64.0   162.0  581  0:09:41    ⋯
409 48181 1997-04-17  0     22  1       1       68.0   153.0  351  0:05:51    ⋯
410 48183 1998-03-20 NA     21  0       1       63.5   168.5  639  0:10:39    ⋯
411 48298 2000-02-20  1     19  0       1       69.0   148.0  451  0:07:31    ⋯
412 48501 1999-04-22 NA     20  1       1       69.0   141.5  405  0:06:45    ⋯
413 48557 1998-02-16  1     21  1       1         NA   149.0  320  0:05:20    ⋯
414 48561 2000-09-05  1     18  0       1       72.5   149.0  571  0:09:31    ⋯
415 48573 1999-02-17  1     20  1       2       66.0   150.5  396  0:06:36    ⋯
416 48592 1999-07-03  0     20  1       3       75.0   215.5  453  0:07:33    ⋯
417 48611 2000-03-29  1     19  1       1       64.0   126.0  447  0:07:27    ⋯
418 48653 1999-09-21  1     19  0       2       63.5   121.0  611  0:10:11    ⋯
419 48775 2001-05-30  0     18  1       1       64.0   159.0  458  0:07:38    ⋯
420 48835 1999-05-18  1     20  0       1       70.0   210.0  718  0:11:58    ⋯
421 49070 1997-05-08  0     22  0       1       69.5   196.5  589  0:09:49    ⋯
422 49116 1999-01-15  1     20  1       1       63.0   140.5  447  0:07:27    ⋯
423 49135 1994-03-19  0     25  0       1       74.5   250.5  506  0:08:26    ⋯
424 49176 1999-02-24 NA     20  0       1       71.5   146.5  585  0:09:45    ⋯
425 49212 1998-03-14  0     21  0       1       66.0   190.0  430  0:07:10    ⋯
426 49370 1998-11-01  0     20  0       1       71.0   181.5  507  0:08:27    ⋯
427 49407 2000-04-18  0     19  1       1       74.0   185.5  397  0:06:37    ⋯
428 49546 1999-09-30  1     19  0       3       62.5   112.0  688  0:11:28    ⋯
429 49627 1999-06-03 NA     20  0       3       66.0   189.5  434  0:07:14    ⋯
430 49729 2000-07-05  1     19  0       2       68.5      NA  459  0:07:39    ⋯
431 49833 2000-01-31  1     19  0       1       64.0   137.0  575  0:09:35    ⋯
432 49844 1999-07-11  0     20  0       3       71.5   223.0  404  0:06:44    ⋯
433 49851             0     NA  1       1       73.5   164.0  410  0:06:50    ⋯
434 49863 1999-08-28  1     20  0       1       61.5   125.0   NA             ⋯
435 49977             0     NA  1       1       70.0   182.0  396  0:06:36    ⋯
    Math Science E_1 E_6 E_11 E_16 E_21 E_26 E_31 E_36
1   67   65      3   4   4    3    3    2    4    3
2   72   73      4   3   3    3    5    3    4    2
3   76   81      4   5   2    3    5    3    4    4
4   66   69      3   5   3    1    5    3    5    3
5   66   68      5   1   7    5    2    5    1    7
6   60   61      3   4   4    2    2    3    4    3
7   69   78      5   2   4    4    3    3    3    4
8   NA   62      4   5   3    2    4    4    5    3
9   72   66      3   2   4    4    4    3    3    2
10  70   67      2   5   2    4    5    2    5    2
11  49   60      4   3   4    3    3    3    3    5
12  82   80      5   3   2    4    6    3    4    2
13  60   69      6   3   4    4    3    6    2    6
14  56   54      5   4   3    4    5    4    4    3
15  67   52      5   1   7    5    1    6    1    6
16  77   69      6   4   2    4    3    5    3    4
17  73   75      5   4   5    4    3    5    3    4
18  79   69      5   2   5    6    2    6    1    4
19  71   63      6   4   5    6    1    7    2    6
20  70   61      4   4   3    3    4    4    3    5
21  67   73      6   2   5    6    1    7    2    5
22  69   66      6   3   4    5    4    5    4    2
23  NA   56      5   3   5    4    2    4    2    4
24  67   68      6   2   5    7    4    5    2    4
25  61   67      4   4   4    4    2    5    2    5
26  65   81      3   4   3    4    5    3    5    1
27  65   55      6   3   6    5    2    5    2    5
28  71   73      5   3   5    4    3    5    3    5
29  75   71      7   1   5    7    3    6    2    5
30  65   64      5   3   5    4    3    4    3    5
⋮   ⋮    ⋮       ⋮   ⋮   ⋮    ⋮    ⋮    ⋮    ⋮    ⋮
406 65   69      6   2   6    6    2    6    1    5
407 72   66      4   4   2    4    5    2    4    2
408 NA   68      5   3   4    4    3    3    3    5
409 62   71      4   4   3    4    4    5    4    3
410 82   77      4   4   2    2    5    2    4    4
411 71   73      2   2   4    4    5    2    3    4
412 66   66      4   4   2    2    5    3    5    3
413 48   65      5   3   3    2    3    4    4    3
414 72   73      6   2   6    6    2    6    1    7
415 63   60      5   1   6    6    3    5    2    4
416 67   68      4   5   4    2    3    4    4    4
417 73   NA      5   4   3    3    5    3    4    4
418 65   61      5   2   5    5    2    5    2    5
419 65   62      6   2   6    5    2    6    2    6
420 73   72      5   2   6    4    2    4    2    4
421 55   61      5   2   5    5    3    4    3    4
422 69   79      6   2   6    5    3    6    2    7
423 64   66      7   3   5    6    5    6    2    6
424 69   68      5   2   5    4    4    5    2    6
425 76   72      4   4   4    4    3    3    4    4
426 70   67      5   2   5    5    2    5    2    5
427 69   72      3   3   5    4    4    4    3    4
428 65   NA      6   2   5    5    4    5    2    5
429 70   64      5   4   4    4    3    5    4    4
430 71   85      4   6   1    3    6    3    5    2
431 74   68      4   5   4    3    4    4    4    5
432 66   NA      6   3   3    4    5    3    3    4
433 59   71      5   2   5    4    2    5    2    5
434 70   82      4   4   2    3    6    3    4    3
435 77   72      3   6   2    3    6    3    5    2

  ids   bday       Gender Age Athlete Smoking Height Weight Mile MileMinDur ⋯
1 20055 1995-08-06 0      24  1        1      64.5   127.5  494  0:08:14    ⋯
2 20075            0      NA  0        1      74.0   195.5  441  0:07:21    ⋯
3 20087            0      NA  0        1      68.5   153.0   NA             ⋯
4 20088 2001-01-08 1      18  0       NA      67.5   158.5  514  0:08:34    ⋯
5 20135 1998-12-26 0      20  0        1      75.0   152.0  450  0:07:30    ⋯
6 20161 2000-12-02 1      18  1        1      73.5   177.5  403  0:06:43    ⋯
  Math Science E_1 E_6 E_11 E_16 E_21 E_26 E_31 E_36
1 67   65      3   4   4    3    3    2    4    3
2 72   73      4   3   3    3    5    3    4    2
3 76   81      4   5   2    3    5    3    4    4
4 66   69      3   5   3    1    5    3    5    3
5 66   68      5   1   7    5    2    5    1    7
6 60   61      3   4   4    2    2    3    4    3

    ids   bday       Gender Age Athlete Smoking Height Weight Mile MileMinDur ⋯
430 49729 2000-07-05 1      19  0       2       68.5    NA    459  0:07:39    ⋯
431 49833 2000-01-31 1      19  0       1       64.0   137    575  0:09:35    ⋯
432 49844 1999-07-11 0      20  0       3       71.5   223    404  0:06:44    ⋯
433 49851            0      NA  1       1       73.5   164    410  0:06:50    ⋯
434 49863 1999-08-28 1      20  0       1       61.5   125     NA             ⋯
435 49977            0      NA  1       1       70.0   182    396  0:06:36    ⋯
    Math Science E_1 E_6 E_11 E_16 E_21 E_26 E_31 E_36
430 71   85      4   6   1    3    6    3    5    2
431 74   68      4   5   4    3    4    4    4    5
432 66   NA      6   3   3    4    5    3    3    4
433 59   71      5   2   5    4    2    5    2    5
434 70   82      4   4   2    3    6    3    4    3
435 77   72      3   6   2    3    6    3    5    2

 [1] "ids"          "bday"         "Gender"       "Age"          "Athlete"
 [6] "Smoking"      "Height"       "Weight"       "Mile"         "MileMinDur"
[11] "Rank"         "Major"        "expgradyear"  "expgradmonth" "State"
[16] "LiveOnCampus" "HowCommute"   "CommuteTime"  "SleepTime"    "StudyTime"
[21] "English"      "Reading"      "Math"         "Science"      "E_1"
[26] "E_6"          "E_11"         "E_16"         "E_21"         "E_26"
[31] "E_31"         "E_36"

'data.frame':	435 obs. of  32 variables:
 $ ids         : int  20055 20075 20087 20088 20135 20161 20188 20215 20250 20354 ...
 $ bday        : chr  "1995-08-06" "" "" "2001-01-08" ...
 $ Gender      : int  0 0 0 1 0 1 0 0 NA 1 ...
 $ Age         : int  24 NA NA 18 20 18 18 22 24 20 ...
 $ Athlete     : int  1 0 0 0 0 1 0 0 0 0 ...
 $ Smoking     : int  1 1 1 NA 1 1 1 2 1 1 ...
 $ Height      : num  64.5 74 68.5 67.5 75 73.5 76 76 66.5 62.5 ...
 $ Weight      : num  128 196 153 158 152 ...
 $ Mile        : int  494 441 NA 514 450 403 NA 563 653 684 ...
 $ MileMinDur  : chr  "0:08:14" "0:07:21" "" "0:08:34" ...
 $ Rank        : int  3 1 2 1 3 2 1 1 3 2 ...
 $ Major       : chr  "" "journalism" "" "Art history" ...
 $ expgradyear : int  2022 2024 2024 2024 2020 2025 2022 2024 NA 2023 ...
 $ expgradmonth: chr  "December" "December" "May" "December" ...
 $ State       : chr  "In state" "In state" "In state" "In state" ...
 $ LiveOnCampus: int  0 0 1 1 0 0 1 1 0 1 ...
 $ HowCommute  : int  3 3 NA NA 3 3 NA NA 4 NA ...
 $ CommuteTime : int  31 25 NA NA 25 24 NA NA 35 NA ...
 $ SleepTime   : int  5 7 5 NA NA 6 8 12 6 8 ...
 $ StudyTime   : int  6 2 6 8 13 9 6 4 12 5 ...
 $ English     : int  64 74 87 90 71 68 84 78 81 93 ...
 $ Reading     : int  79 67 89 94 70 64 78 75 NA 86 ...
 $ Math        : int  67 72 76 66 66 60 69 NA 72 70 ...
 $ Science     : int  65 73 81 69 68 61 78 62 66 67 ...
 $ E_1         : int  3 4 4 3 5 3 5 4 3 2 ...
 $ E_6         : int  4 3 5 5 1 4 2 5 2 5 ...
 $ E_11        : int  4 3 2 3 7 4 4 3 4 2 ...
 $ E_16        : int  3 3 3 1 5 2 4 2 4 4 ...
 $ E_21        : int  3 5 5 5 2 2 3 4 4 5 ...
 $ E_26        : int  2 3 3 3 5 3 3 4 3 2 ...
 $ E_31        : int  4 4 4 5 1 4 3 5 3 5 ...
 $ E_36        : int  3 2 4 3 7 3 4 3 2 2 ...

      ids            bday               Gender            Age
 Min.   :20055   Length:435         Min.   :0.0000   Min.   :18.00
 1st Qu.:27296   Class :character   1st Qu.:0.0000   1st Qu.:19.00
 Median :34028   Mode  :character   Median :1.0000   Median :20.00
 Mean   :34497                      Mean   :0.5169   Mean   :20.25
 3rd Qu.:40902                      3rd Qu.:1.0000   3rd Qu.:21.00
 Max.   :49977                      Max.   :1.0000   Max.   :28.00
                                    NA's   :21       NA's   :44
    Athlete       Smoking          Height          Weight           Mile
 Min.   :0.0   Min.   :1.000   Min.   :58.50   Min.   : 94.5   Min.   :301.0
 1st Qu.:0.0   1st Qu.:1.000   1st Qu.:65.00   1st Qu.:136.9   1st Qu.:401.0
 Median :0.0   Median :1.000   Median :68.50   Median :157.0   Median :463.0
 Mean   :0.4   Mean   :1.294   Mean   :68.43   Mean   :160.0   Mean   :489.2
 3rd Qu.:1.0   3rd Qu.:1.000   3rd Qu.:72.00   3rd Qu.:181.1   3rd Qu.:558.0
 Max.   :1.0   Max.   :3.000   Max.   :78.00   Max.   :261.5   Max.   :896.0
               NA's   :30      NA's   :27      NA's   :47      NA's   :14
  MileMinDur             Rank          Major            expgradyear
 Length:435         Min.   :1.000   Length:435         Min.   :2019
 Class :character   1st Qu.:1.000   Class :character   1st Qu.:2022
 Mode  :character   Median :2.000   Mode  :character   Median :2023
                    Mean   :2.059                      Mean   :2023
                    3rd Qu.:3.000                      3rd Qu.:2024
                    Max.   :4.000                      Max.   :2026
                    NA's   :13                         NA's   :60
 expgradmonth          State            LiveOnCampus      HowCommute
 Length:435         Length:435         Min.   :0.0000   Min.   :1.000
 Class :character   Class :character   1st Qu.:0.0000   1st Qu.:3.000
 Mode  :character   Mode  :character   Median :0.0000   Median :3.000
                                       Mean   :0.4869   Mean   :2.765
                                       3rd Qu.:1.0000   3rd Qu.:3.000
                                       Max.   :1.0000   Max.   :4.000
                                       NA's   :14       NA's   :209
  CommuteTime      SleepTime        StudyTime         English
 Min.   : 2.00   Min.   : 3.000   Min.   : 0.000   Min.   : 61.00
 1st Qu.:18.00   1st Qu.: 6.000   1st Qu.: 4.000   1st Qu.: 78.00
 Median :25.00   Median : 7.000   Median : 6.000   Median : 82.00
 Mean   :23.65   Mean   : 7.366   Mean   : 7.089   Mean   : 82.28
 3rd Qu.:30.00   3rd Qu.: 9.000   3rd Qu.: 9.000   3rd Qu.: 87.00
 Max.   :43.00   Max.   :14.000   Max.   :25.000   Max.   :104.00
 NA's   :209     NA's   :25       NA's   :43       NA's   :23
    Reading            Math          Science           E_1
 Min.   : 61.00   Min.   :37.00   Min.   :47.00   Min.   :1.000
 1st Qu.: 75.00   1st Qu.:61.00   1st Qu.:63.00   1st Qu.:4.000
 Median : 81.00   Median :66.00   Median :68.00   Median :4.000
 Mean   : 80.68   Mean   :66.28   Mean   :67.64   Mean   :4.326
 3rd Qu.: 86.00   3rd Qu.:71.50   3rd Qu.:72.00   3rd Qu.:5.000
 Max.   :104.00   Max.   :92.00   Max.   :91.00   Max.   :7.000
 NA's   :18       NA's   :24      NA's   :21
      E_6             E_11           E_16            E_21            E_26
 Min.   :1.000   Min.   :1.00   Min.   :1.000   Min.   :1.000   Min.   :1.000
 1st Qu.:2.000   1st Qu.:3.00   1st Qu.:3.000   1st Qu.:3.000   1st Qu.:3.000
 Median :3.000   Median :4.00   Median :4.000   Median :3.000   Median :4.000
 Mean   :3.218   Mean   :4.03   Mean   :3.821   Mean   :3.503   Mean   :3.945
 3rd Qu.:4.000   3rd Qu.:5.00   3rd Qu.:5.000   3rd Qu.:4.000   3rd Qu.:5.000
 Max.   :7.000   Max.   :7.00   Max.   :7.000   Max.   :6.000   Max.   :7.000

      E_31            E_36
 Min.   :1.000   Min.   :1.000
 1st Qu.:2.000   1st Qu.:3.000
 Median :3.000   Median :4.000
 Mean   :3.147   Mean   :4.232
 3rd Qu.:4.000   3rd Qu.:5.000
 Max.   :6.000   Max.   :7.000

In [ ]:
##### Step 2: Computing new variables ##########################################

#' Use the $ operator to access a single variable within the dataframe (e.g. to find its mean)

$???

  #' See if you can use this to find the mean of variable SleepTime:

  mean(???$???)

#' If the above result returned NA, it's because the variable had missing values.
#' To have R ignore the missing values and calculate the sample mean using the
#' nonmissing observations, add the na.rm=TRUE argument.
mean(???$???, na.rm=TRUE)


#' How can we add a new variable to an existing dataframe?
#' We combine the $ notation with the assignment operator!

???$SleepTimeMinutes <- ???$SleepTime*60

???$missing_SleepTime <- is.na(???$SleepTime)

???$RankLabeled <- factor(???$Rank,
                          levels=c(1, 2, 3, 4),
                          labels=c("Freshman", "Sophomore", "Junior", "Senior"))

???$RankOrdered <- ordered(???$Rank,
                           levels=c(1, 2, 3, 4),
                           labels=c("Freshman", "Sophomore", "Junior", "Senior"))

In [ ]:
##### Step 3: Filtering rows/Access rows within the dataset ####################

#' Use the subset() function with the subset argument to filter the rows in
#' the dataset to just those meeting a logical condition
#'    logical operators in R include:
#'      ==    equal to
#'      !=    not equal to
#'      >     greater than
#'      >=    greater than or equal to
#'      <     less than
#'      <=    less than or equal to
#'      !     "not" (used as prefix in front of functions that return TRUE/FALSE)
#'    logical functions in R include (but are not limited to!):
#'      is.na()       returns TRUE if missing, FALSE if nonmissing
#'      is.numeric()  returns TRUE if input is numeric, FALSE otherwise
#'      is.character()  returns TRUE if input is character, FALSE otherwise

subset(???, subset=???)

##### Step 4: Selecting columns/Access the variables within the dataset ########

#' Use the subset() function to extract multiple columns from the dataset
#' by name, position, or pattern

#' Use vectors to supply the names of more than one variables (replace "var1" and "var2 with actual variable names from the data)
subset(???, select=c(var1, var2))

#' You can add a minus sign (-) in front of the vector to instead REMOVE those variables
subset(???, select=-c(var1, var2))

In [ ]:
## Part 3: Data Analysis ###################################################

#' Try making a frequency table of variable Rank using table()

table(???)

#' If you want to add the totals, wrap the table() function in addmargins() function:

addmargins(table(???))

#' Does this number match the number of rows in the dataset? If not,
#' what do you think the issue is?


#' Compute Pearson correlation between two variables using cor()
#'    SleepTime and StudyTime

cor(???, ???)

#' What happens when we pass the entire dataframe object to the cor() function?

cor(???)

#' We get an error message if we try to pass the entire dataframe to cor()
#' because the dataframe contains non-numeric variables.
#' Let's create a dataset with just the main numeric variables (SleepTime, StudyTime),
#' which can then safely be passed to cor().
#' The subset() function can select a range of columns using the select argument.




#' Fit linear regression model using lm()
#' The first argument to lm() is the model formula, which follows the syntax:
#'      y ~ x1 + x2 + ...
#'   where y is the dependent variable and x1, x2, ... are independent variables

lm(y ~ x1 + x2, data=???)

#' Model formula with interaction (this syntax will fit all main effects and the two-way interaction)
lm(y ~ x1*x2, data=???)